export const TOPICS=[
{id:"robot",name:"건설 로봇",category:"기술",terms:["건설 로봇","건설로봇","construction robot","robotic construction"]},
{id:"bim",name:"BIM",category:"기술",terms:["bim","빌딩정보모델링","building information modeling"]},
{id:"smart",name:"스마트건설",category:"기술",terms:["스마트건설","스마트 건설","smart construction"]},
{id:"modular",name:"모듈러 건축",category:"기술",terms:["모듈러","modular construction","prefabricated building"]},
{id:"cost",name:"공사비",category:"경제",terms:["공사비","공사 원가","construction cost"]},
{id:"market",name:"건설경기",category:"경제",terms:["건설경기","건설 수주","construction market","construction spending"]},
{id:"safety",name:"건설안전",category:"안전",terms:["건설안전","건설 안전","중대재해","construction safety"]},
{id:"housing",name:"재건축·재개발",category:"정책",terms:["재건축","재개발","redevelopment","reconstruction project"]},
{id:"carbon",name:"친환경 건축",category:"기술",terms:["제로에너지","친환경 건축","탄소중립 건축","green building","sustainable construction"]},
{id:"overseas",name:"해외건설",category:"해외",terms:["해외건설","해외 건설","overseas construction","international construction"]}
];
export function decodeXml(input=""){return input.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(whole,entity)=>{const named={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" "};if(entity[0]==="#"){const hex=entity[1]?.toLowerCase()==="x";const code=Number.parseInt(entity.slice(hex?2:1),hex?16:10);return Number.isFinite(code)&&code>=0&&code<=0x10ffff?String.fromCodePoint(code):whole;}return named[entity.toLowerCase()]??whole;}).trim()}
function tag(xml,name){return decodeXml(xml.match(new RegExp("<"+name+"(?:\\s[^>]*)?>([\\s\\S]*?)<\\/"+name+">","i"))?.[1]??"")}
function dateKey(date){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(date)}
export function parseRss(xml,region,now=new Date()){if(!xml.includes("<rss")&&!xml.includes("<item"))throw Error("RSS 형식이 아닙니다.");const min=now.getTime()-7*86400000;return (xml.match(/<item(?:\s[^>]*)?>[\s\S]*?<\/item>/gi)||[]).flatMap(item=>{const original=tag(item,"title"),raw=tag(item,"link"),source=tag(item,"source")||"Google 뉴스",published=new Date(tag(item,"pubDate"));let url;try{url=new URL(raw);if(!["https:","http:"].includes(url.protocol))return []}catch{return []}if(!original||!Number.isFinite(published.getTime())||published.getTime()<min||published.getTime()>now.getTime()+3600000)return [];const title=original.endsWith(" - "+source)?original.slice(0,-source.length-3).trim():original;const lower=title.toLocaleLowerCase();const matches=TOPICS.filter(topic=>topic.terms.some(term=>lower.includes(term.toLocaleLowerCase())));return [{id:region+":"+lower.replace(/\s+/g," "),title,url:url.href,source,region,publishedAt:published.toISOString(),topicIds:matches.map(x=>x.id),category:matches[0]?.category??"종합"}]})}
function feed(q,korean=true){return "https://news.google.com/rss/search?"+new URLSearchParams({q:q+" when:7d",hl:korean?"ko":"en-US",gl:korean?"KR":"US",ceid:korean?"KR:ko":"US:en"}).toString()}
export const FEEDS=[{url:feed("건설"),region:"국내",label:"국내 건설"},{url:feed("건축"),region:"국내",label:"국내 건축"},{url:feed("construction industry",false),region:"해외",label:"해외 건설"}];
export async function getDashboard({fetcher=fetch,now=new Date()}={}){const results=await Promise.allSettled(FEEDS.map(async feed=>{const res=await fetcher(feed.url,{next:{revalidate:1800},signal:AbortSignal.timeout(9000)});if(!res.ok)throw Error(feed.label+" HTTP "+res.status);return {feed,news:parseRss(await res.text(),feed.region,now)}}));const success=results.filter(x=>x.status==="fulfilled").map(x=>x.value);if(!success.length)throw Error("뉴스 RSS에 접속할 수 없습니다. 잠시 후 다시 시도해 주세요.");const failures=results.map((x,i)=>x.status==="rejected"?FEEDS[i].label:null).filter(Boolean);const map=new Map();for(const group of success)for(const article of group.news){const key=article.title.toLocaleLowerCase().replace(/[^가-힣a-z0-9]/gi,"");if(!map.has(key))map.set(key,article)}const news=[...map.values()].sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));const days=Array.from({length:7},(_,i)=>dateKey(new Date(now.getTime()-(6-i)*86400000)));const topics=TOPICS.map(t=>{const matches=news.filter(a=>a.topicIds.includes(t.id));return {id:t.id,name:t.name,category:t.category,count:matches.length,series:days.map(date=>({date,value:matches.filter(a=>dateKey(new Date(a.publishedAt))===date).length}))}}).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,"ko"));return {updatedAt:now.toISOString(),sampleSize:news.length,feedsSucceeded:success.length,feedsTotal:FEEDS.length,failedFeeds:failures,topics,news:[...news.filter(a=>a.region==="국내").slice(0,5),...news.filter(a=>a.region==="해외").slice(0,2)],note:"수집된 Google 뉴스 RSS의 최근 7일 기사 제목을 대상으로 한 키워드 언급량입니다. 검색량이나 전체 언론의 보도량이 아닙니다."}}
